"use client";

import { useEffect, useState, useCallback } from "react";

/**
 * A single search result from Pagefind.
 * Typed manually — pagefind is loaded at runtime and has no bundled types.
 */
interface PagefindResult {
  url: string;
  excerpt: string;
  meta?: { title?: string };
}

/**
 * Site-wide full-text search modal powered by Pagefind.
 *
 * Opens with Cmd+K (or Ctrl+K). Closes with Escape or backdrop click.
 * Also listens for a custom "vhyxseal:opensearch" event so the
 * Header's search button can trigger it without prop drilling.
 *
 * Note: search results are only populated after running `next build`
 * (Pagefind builds its index from the static output). In dev mode
 * the modal opens but results will be empty — this is expected.
 *
 * Zero hardcoded colors — all via --docs-* CSS custom properties.
 */
export function Search(): React.ReactElement {
  const [open, setOpen] = useState<boolean>(false);
  const [query, setQuery] = useState<string>("");
  const [results, setResults] = useState<PagefindResult[]>([]);

  // Keyboard and custom-event listeners
  useEffect(() => {
    const handleKey = (e: KeyboardEvent): void => {
      if ((e.metaKey || e.ctrlKey) && e.key === "k") {
        e.preventDefault();
        setOpen((o) => !o);
      }
      if (e.key === "Escape") {
        setOpen(false);
      }
    };

    const handleOpenEvent = (): void => {
      setOpen(true);
    };

    window.addEventListener("keydown", handleKey);
    window.addEventListener("vhyxseal:opensearch", handleOpenEvent);
    return (): void => {
      window.removeEventListener("keydown", handleKey);
      window.removeEventListener("vhyxseal:opensearch", handleOpenEvent);
    };
  }, []);

  const handleSearch = useCallback(async (q: string): Promise<void> => {
    setQuery(q);
    if (q.trim() === "") {
      setResults([]);
      return;
    }
    try {
      // @ts-expect-error — pagefind is loaded at runtime from /pagefind/pagefind.js
      // (generated by the pagefind CLI post-build). Not a bundled module.
      // webpackIgnore prevents Next.js from trying to resolve this at build time.
      const pagefind = (await import(/* webpackIgnore: true */ "/pagefind/pagefind.js")) as {
        search: (q: string) => Promise<{
          results: Array<{ data: () => Promise<PagefindResult> }>;
        }>;
      };
      const search = await pagefind.search(q);
      const data = await Promise.all(
        search.results.slice(0, 8).map((r) => r.data()),
      );
      setResults(data);
    } catch {
      // Pagefind index not available (dev mode or build not run yet)
      setResults([]);
    }
  }, []);

  if (!open) {
    return <></>;
  }

  return (
    <>
      {/* Backdrop */}
      <div
        role="presentation"
        onClick={() => {
          setOpen(false);
        }}
        style={{
          position: "fixed",
          inset: 0,
          backgroundColor: "rgba(0,0,0,0.5)",
          zIndex: 200,
        }}
      />

      {/* Modal */}
      <div
        role="dialog"
        aria-modal="true"
        aria-label="Search documentation"
        style={{
          position: "fixed",
          top: "20%",
          left: "50%",
          transform: "translateX(-50%)",
          width: "min(600px, 90vw)",
          backgroundColor: "var(--docs-surface)",
          border: "1px solid var(--docs-border)",
          borderRadius: "12px",
          zIndex: 201,
          overflow: "hidden",
        }}
      >
        <input
          autoFocus
          placeholder="Search docs..."
          value={query}
          onChange={(e) => {
            void handleSearch(e.target.value);
          }}
          style={{
            width: "100%",
            padding: "16px 20px",
            fontSize: "16px",
            background: "none",
            border: "none",
            borderBottom: "1px solid var(--docs-border)",
            color: "var(--docs-text)",
            outline: "none",
            boxSizing: "border-box",
          }}
        />

        {results.length > 0 && (
          <ul
            style={{
              listStyle: "none",
              padding: "8px 0",
              maxHeight: "400px",
              overflowY: "auto",
              margin: 0,
            }}
          >
            {results.map((r, i) => (
              <li key={i}>
                <a
                  href={r.url}
                  onClick={() => {
                    setOpen(false);
                  }}
                  style={{
                    display: "block",
                    padding: "12px 20px",
                    color: "var(--docs-text)",
                    textDecoration: "none",
                  }}
                >
                  <div style={{ fontWeight: 600, fontSize: "14px" }}>
                    {r.meta?.title}
                  </div>
                  <div
                    style={{
                      fontSize: "13px",
                      color: "var(--docs-text-muted)",
                      marginTop: "4px",
                    }}
                    // biome-ignore lint: pagefind excerpt is server-generated, sanitized HTML
                    dangerouslySetInnerHTML={{ __html: r.excerpt }}
                  />
                </a>
              </li>
            ))}
          </ul>
        )}

        {query !== "" && results.length === 0 && (
          <div
            style={{
              padding: "20px",
              color: "var(--docs-text-muted)",
              fontSize: "14px",
            }}
          >
            No results for &ldquo;{query}&rdquo;
          </div>
        )}
      </div>
    </>
  );
}
