import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { print } from "../utils/output.js";

/**
 * Options for the init command.
 */
export interface InitOptions {
  /** Path to the project root. Defaults to process.cwd(). */
  projectPath?: string;
  /** Overwrite an existing config file. */
  force?: boolean;
  /** Domain to embed in the generated config. */
  domain?: string;
}

/**
 * Result returned by the init command.
 */
export interface InitResult {
  /** Whether the config file was created or overwritten. */
  configCreated: boolean;
  /** Absolute path to the config file. */
  configPath: string;
  /** Whether a config file already existed before this call. */
  alreadyExisted: boolean;
  /** Human-readable next steps for the developer. */
  nextSteps: string[];
}

const NEXT_STEPS: readonly string[] = [
  "1. Edit vhyxseal.config.ts and set your domain",
  "2. Install @vhyxseal/core: pnpm add @vhyxseal/core",
  "3. Wrap your components with contracts using defineContract()",
  "4. Visit https://vhyxseal.dev/docs/getting-started for the full guide",
] as const;

function buildConfigContent(domain: string): string {
  return `import type { ManifestConfig } from "@vhyxseal/core";

/**
 * VhyxSeal configuration.
 * Generated by: vhyxseal init
 * Docs: https://vhyxseal.dev/docs/getting-started
 */
export const vhyxsealConfig: ManifestConfig = {
  domain: "${domain}",
  domainVerified: false,
  verificationToken: "",
  cacheDurationSeconds: 3600,
};
`;
}

/**
 * Initializes a VhyxSeal project configuration.
 * Creates vhyxseal.config.ts and optionally updates package.json.
 *
 * @param options - Init options including project path, domain, and force flag
 * @returns InitResult with config path and next steps
 * @example
 * const result = await init({ projectPath: process.cwd(), domain: 'my-app.io' });
 * console.log(result.configPath);
 */
export async function init(options: InitOptions = {}): Promise<InitResult> {
  const projectPath = options.projectPath ?? process.cwd();
  const force = options.force ?? false;
  const domain = options.domain ?? "your-domain.com";
  const configPath = join(projectPath, "vhyxseal.config.ts");

  const alreadyExisted = existsSync(configPath);

  if (alreadyExisted && !force) {
    print(`\n⚠️  vhyxseal.config.ts already exists at ${configPath}`);
    print(`   Run with --force to overwrite.`);

    return {
      configCreated: false,
      configPath,
      alreadyExisted: true,
      nextSteps: Array.from(NEXT_STEPS),
    };
  }

  const content = buildConfigContent(domain);
  writeFileSync(configPath, content, "utf-8");

  // Update package.json if it exists in the project root
  const pkgPath = join(projectPath, "package.json");
  if (existsSync(pkgPath)) {
    try {
      const raw = readFileSync(pkgPath, "utf-8");
      const pkg = JSON.parse(raw) as Record<string, unknown>;
      const deps =
        (pkg["dependencies"] as Record<string, string> | undefined) ?? {};

      if (!deps["@vhyxseal/core"]) {
        deps["@vhyxseal/core"] = "^0.1.0";
        pkg["dependencies"] = deps;
        writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n", "utf-8");
      }
    } catch {
      // Non-fatal — do not block config creation on package.json parse errors
    }
  }

  print(`\n✅ Created vhyxseal.config.ts at ${configPath}`);
  NEXT_STEPS.forEach((step) => print(`   ${step}`));

  return {
    configCreated: true,
    configPath,
    alreadyExisted,
    nextSteps: Array.from(NEXT_STEPS),
  };
}
