import { CodeBlock } from "../../components/CodeBlock";
import { OnThisPage } from "../../components/OnThisPage";
import { PrevNext } from "../../components/PrevNext";

// ── Code examples ─────────────────────────────────────────────────────────

const signingCode = `// Manifest signing — configured automatically by @vhyxseal/nextjs
// Manual signing API from @vhyxseal/core:
import { signManifest, verifyManifest } from '@vhyxseal/core'

// Sign at build time or request time
const signed = signManifest(manifest, privateKey)
// { signature: "sha256:...", signedAt: "..." }

// Verify before trusting any contract data
const result = verifyManifest(signedManifest, publicKey)
// { valid: true, domain: "example.com", ... }
// On failure: all safety defaults apply — agents cannot act`;

const injectionCode = `// Sanitization runs automatically on all string fields
// Zero configuration required — built into defineContract()

import { sanitizeContract } from '@vhyxseal/core'

// Field length limits (enforced, not configurable):
// description:              max 500 characters
// intent:                   max 50 characters
// consequence:              max 300 characters
// condition.description:    max 200 characters

// 14 injection pattern categories detected:
// prompt injection, jailbreak, SSRF, XSS, path traversal,
// SQL injection, code execution, and more`;

const actionTokenCode = `// Action token — auto-generated by @vhyxseal/nextjs for every agent action
// Six-step verification:
//
// 1. Token ID exists in issued map
// 2. Date.now() < token.expiresAt  (60-second window)
// 3. token.contractId === expected.contractId
// 4. token.componentId === expected.componentId
// 5. token.intent === expected.intent
// 6. token.used === false  →  set token.used = true (atomic)
//
// Replay attack: step 6 fails — token already consumed.
// Expired token: step 2 fails — 60-second TTL enforced.`;

const domainCode = `// Domain verification — site must prove ownership
// Verified token issued by VhyxSeal registry after confirmation

import { issueDomainToken, verifyDomainToken } from '@vhyxseal/core'

const { token } = await issueDomainToken("example.com")
// token is stored in manifest as verificationToken

const valid = await verifyDomainToken("example.com", token)
// true if ownership verified, false if not`;

// ── Styles ────────────────────────────────────────────────────────────────

const h1Style: React.CSSProperties = {
  fontSize: "clamp(1.75rem, 4vw, 2.5rem)",
  fontWeight: 800,
  letterSpacing: "-0.03em",
  color: "var(--docs-text)",
  marginBottom: "8px",
  marginTop: 0,
};

const h2Style: React.CSSProperties = {
  fontSize: "1.375rem",
  fontWeight: 700,
  letterSpacing: "-0.02em",
  color: "var(--docs-text)",
  marginBottom: "20px",
  marginTop: "56px",
  paddingTop: "40px",
  borderTop: "1px solid var(--docs-border)",
};

const h3Style: React.CSSProperties = {
  fontSize: "1rem",
  fontWeight: 700,
  color: "var(--docs-text)",
  marginBottom: "8px",
  marginTop: "28px",
};

const leadStyle: React.CSSProperties = {
  fontSize: "1.0625rem",
  color: "var(--docs-text-muted)",
  lineHeight: 1.75,
  marginBottom: "24px",
  maxWidth: "660px",
};

const tableStyle: React.CSSProperties = {
  width: "100%",
  borderCollapse: "collapse",
  fontSize: "13px",
  marginBottom: "24px",
};

const thStyle: React.CSSProperties = {
  textAlign: "left",
  padding: "8px 12px",
  color: "var(--docs-text-muted)",
  borderBottom: "1px solid var(--docs-border)",
  fontWeight: 600,
  fontSize: "11px",
  textTransform: "uppercase",
  letterSpacing: "0.06em",
};

const tdStyle: React.CSSProperties = {
  padding: "8px 12px",
  borderBottom: "1px solid var(--docs-border)",
  color: "var(--docs-text)",
  verticalAlign: "top",
};

const warningBoxStyle: React.CSSProperties = {
  border: "1px solid var(--vhyxseal-color-inferred)",
  borderRadius: "8px",
  padding: "16px 20px",
  backgroundColor: "var(--docs-surface)",
  marginBottom: "24px",
};

const limitationStyle: React.CSSProperties = {
  marginBottom: "28px",
  paddingBottom: "28px",
  borderBottom: "1px solid var(--docs-border)",
};

/**
 * Security guide — four sections.
 *
 * Section 1: Threat model — what VhyxSeal defends and does not defend.
 * Section 2: What is implemented — each layer with code example.
 * Section 3: Known limitations — exact framing specified, not softened.
 * Section 4: Security reporting — contact and SLA.
 *
 * Zero hardcoded colors — all via --docs-* or --vhyxseal-* CSS custom properties.
 */
export default function SecurityPage(): React.ReactElement {
  return (
    <>
      <OnThisPage />
      <h1 style={h1Style}>Security</h1>
      <p style={leadStyle}>
        VhyxSeal sits between AI agents and websites. Security is foundational,
        not a feature added later. Eight layers are designed from Stage 1.
        This guide covers the threat model, what is implemented, what is
        not yet enforced, and how to report vulnerabilities.
      </p>

      {/* ── Section 1 — Threat Model ───────────────────────────────── */}
      <section>
        <h2 style={h2Style}>Threat Model</h2>

        <h3 style={h3Style}>What VhyxSeal defends against</h3>
        <div style={{ overflowX: "auto" }}>
          <table style={tableStyle}>
            <thead>
              <tr>
                <th style={thStyle}>Threat</th>
                <th style={thStyle}>Mitigation</th>
              </tr>
            </thead>
            <tbody>
              {[
                ["Manifest poisoning", "HMAC-SHA256 signing — agents reject unsigned or mis-signed manifests"],
                ["Prompt injection", "14-pattern injection detection, field length limits, structural trust over textual trust"],
                ["Fake manifest spoofing", "Domain binding — manifest is cryptographically tied to its verified domain"],
                ["Agent impersonation", "Agent identification policy in AgentPolicy.allowedAgents"],
                ["Contract replay attacks", "Single-use action tokens with 60-second TTL — each token consumed once"],
                ["Supply chain attacks", "Core has zero runtime dependencies, GPG-signed releases, two-person release approval"],
                ["Data exfiltration via conditions", "Abstract field references enforced — internal field names never exposed"],
              ].map(([threat, mitigation]) => (
                <tr key={String(threat)}>
                  <td style={{ ...tdStyle, fontWeight: 500 }}>{threat}</td>
                  <td style={{ ...tdStyle, color: "var(--docs-text-muted)" }}>{mitigation}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <h3 style={{ ...h3Style, marginTop: "32px" }}>
          What VhyxSeal does NOT defend against
        </h3>
        <p
          style={{
            fontSize: "14px",
            color: "var(--docs-text-muted)",
            lineHeight: 1.7,
            marginBottom: "12px",
            maxWidth: "600px",
          }}
        >
          These are out of scope by design. Use appropriate tools for each:
        </p>
        <ul
          style={{
            padding: "0 0 0 20px",
            margin: "0 0 24px",
            color: "var(--docs-text-muted)",
            fontSize: "14px",
            lineHeight: 2,
          }}
        >
          <li>Consuming application security vulnerabilities (use security audits)</li>
          <li>Server authentication and authorization (use your auth layer)</li>
          <li>Network-level attacks — use HTTPS (TLS at infrastructure level)</li>
          <li>Zero-day vulnerabilities in agent models (beyond scope of contract layer)</li>
        </ul>
      </section>

      {/* ── Section 2 — What Is Implemented ───────────────────────── */}
      <section>
        <h2 style={h2Style}>What Is Implemented</h2>

        <h3 style={h3Style}>Layer 1 — HMAC-SHA256 Manifest Signing</h3>
        <p style={{ ...leadStyle, fontSize: "14px", marginBottom: "12px" }}>
          Every manifest is cryptographically signed at build time. Agents
          verify the signature before trusting any contract data. Signature
          failure triggers maximum safety defaults — agents cannot act.
          Currently a stub — see Known Limitations below.
        </p>
        <CodeBlock code={signingCode} lang="typescript" />

        <h3 style={{ ...h3Style, marginTop: "32px" }}>Layer 2 — Injection Detection (14 pattern categories)</h3>
        <p style={{ ...leadStyle, fontSize: "14px", marginBottom: "12px" }}>
          All string fields in contracts are sanitized before being surfaced
          to AI agents. Detection runs on 14 pattern categories including
          prompt injection, jailbreak, SSRF, XSS, path traversal, and SQL
          injection. Field length limits are hard limits — not suggestions.
          Structural trust rule: agent safety decisions derive from typed
          fields (safetyLevel, requiresConfirmation, destructive), never from
          text description fields alone.
        </p>
        <CodeBlock code={injectionCode} lang="typescript" />

        <h3 style={{ ...h3Style, marginTop: "32px" }}>Layer 3 — Action Tokens (6-step verification)</h3>
        <p style={{ ...leadStyle, fontSize: "14px", marginBottom: "12px" }}>
          Every agent action generates a single-use token that expires in 60
          seconds. Six-step verification is a security decision, not an
          implementation choice. The order of steps is fixed.
        </p>
        <CodeBlock code={actionTokenCode} lang="typescript" />

        <h3 style={{ ...h3Style, marginTop: "32px" }}>Layer 4 — Domain Verification</h3>
        <p style={{ ...leadStyle, fontSize: "14px", marginBottom: "12px" }}>
          Every manifest is cryptographically bound to its verified domain.
          Agents check manifest domain matches actual domain. Mismatch triggers
          full manifest rejection.
        </p>
        <CodeBlock code={domainCode} lang="typescript" />

        <h3 style={{ ...h3Style, marginTop: "32px" }}>Layer 5 — Field Length Limits</h3>
        <p style={{ ...leadStyle, fontSize: "14px", marginBottom: "0" }}>
          Hard limits enforced at schema validation level. Not configurable.
        </p>
        <div style={{ overflowX: "auto", marginTop: "12px" }}>
          <table style={tableStyle}>
            <thead>
              <tr>
                <th style={thStyle}>Field</th>
                <th style={thStyle}>Limit</th>
              </tr>
            </thead>
            <tbody>
              {[
                ["description", "500 characters"],
                ["intent", "50 characters"],
                ["consequence", "300 characters"],
                ["condition.description", "200 characters"],
              ].map(([field, limit]) => (
                <tr key={String(field)}>
                  <td style={{ ...tdStyle, fontFamily: "monospace", fontSize: "13px" }}>{field}</td>
                  <td style={{ ...tdStyle, color: "var(--docs-text-muted)" }}>{limit}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      {/* ── Section 3 — Known Limitations ─────────────────────────── */}
      <section>
        <h2 style={h2Style}>Known Limitations</h2>

        <div style={warningBoxStyle}>
          <p
            style={{
              margin: 0,
              fontSize: "14px",
              color: "var(--docs-text-muted)",
              lineHeight: 1.7,
            }}
          >
            The following capabilities are defined in this RFC but not yet
            enforced in 1.0.0-rc.1:
          </p>
        </div>

        <div style={limitationStyle}>
          <h3 style={{ ...h3Style, marginTop: 0 }}>Rate Limit Enforcement</h3>
          <p
            style={{
              fontSize: "14px",
              color: "var(--docs-text-muted)",
              lineHeight: 1.75,
              maxWidth: "620px",
            }}
          >
            <code
              style={{
                backgroundColor: "var(--docs-code-bg)",
                padding: "2px 5px",
                borderRadius: "4px",
                fontSize: "12px",
              }}
            >
              AgentPolicy.rateLimits
            </code>{" "}
            is schema-defined but not enforced by VhyxSeal middleware in this
            release. Enforcement implementations are scheduled for 1.1.0.
          </p>
          <p
            style={{
              fontSize: "14px",
              color: "var(--docs-text-muted)",
              lineHeight: 1.75,
              maxWidth: "620px",
              marginBottom: 0,
            }}
          >
            <strong style={{ color: "var(--docs-text)" }}>Current mitigation:</strong> implement
            rate limiting at your infrastructure layer (Vercel, Cloudflare, nginx).
          </p>
        </div>

        <div style={{ ...limitationStyle, borderBottom: "none" }}>
          <h3 style={{ ...h3Style, marginTop: 0 }}>Registry Backend</h3>
          <p
            style={{
              fontSize: "14px",
              color: "var(--docs-text-muted)",
              lineHeight: 1.75,
              maxWidth: "620px",
              marginBottom: 0,
            }}
          >
            Domain verification tokens require a trusted registry to be
            meaningful. A hosted registry is in development. Until then,
            domain verification provides format validation only.
          </p>
        </div>
      </section>

      {/* ── Section 4 — Security Reporting ────────────────────────── */}
      <section style={{ paddingBottom: "80px" }}>
        <h2 style={h2Style}>Security Reporting</h2>
        <p style={leadStyle}>
          We take security vulnerabilities seriously. Please report
          responsibly — do not create public GitHub issues for security bugs.
        </p>

        <div
          style={{
            border: "1px solid var(--docs-border)",
            borderRadius: "8px",
            padding: "24px",
            backgroundColor: "var(--docs-surface)",
            fontSize: "14px",
            lineHeight: 1.8,
            color: "var(--docs-text-muted)",
          }}
        >
          <p style={{ marginTop: 0 }}>
            <strong style={{ color: "var(--docs-text)" }}>Report via:</strong>{" "}
            <a
              href="https://github.com/vhyxara/vhyxseal/security"
              target="_blank"
              rel="noopener noreferrer"
              style={{ color: "var(--docs-link)" }}
            >
              GitHub Security Advisories
            </a>{" "}
            or{" "}
            <a
              href="mailto:security@vhyxara.dev"
              style={{ color: "var(--docs-link)" }}
            >
              security@vhyxara.dev
            </a>
          </p>
          <p>
            <strong style={{ color: "var(--docs-text)" }}>Acknowledgement:</strong>{" "}
            48 hours
          </p>
          <p style={{ marginBottom: 0 }}>
            <strong style={{ color: "var(--docs-text)" }}>
              Patch commitment for critical:
            </strong>{" "}
            14 days
          </p>
        </div>

        <p
          style={{
            fontSize: "13px",
            color: "var(--docs-text-muted)",
            marginTop: "16px",
          }}
        >
          See{" "}
          <a
            href="https://github.com/vhyxara/vhyxseal/blob/main/SECURITY.md"
            target="_blank"
            rel="noopener noreferrer"
            style={{ color: "var(--docs-link)" }}
          >
            SECURITY.md
          </a>{" "}
          on GitHub for the full disclosure policy.
        </p>
      </section>
      <PrevNext />
    </>
  );
}
