/**
 * Domain verification — end-to-end HMAC-signed token flow.
 *
 * Wires DomainRegistry (domain lifecycle) and KeyManager (HMAC signing) into
 * a single coherent verification flow. This module is the first real consumer
 * of both registries, closing DEFER 5.
 *
 * Token format: crypto.randomBytes(32).toString('hex') — 64 hex characters.
 * Signing: HMAC-SHA256 over "domain:token" using the active KeyManager key.
 *
 * Security properties:
 *   - Tokens are cryptographically random (Constraint 5 / STAGE-4A-CONSTRAINTS).
 *   - HMAC binds the token to its domain — tokens cannot be replayed across domains.
 *   - Verification uses constant-time comparison (timingSafeEqual) to resist timing attacks.
 *   - verifyDomainToken never throws — all failure paths return false.
 *   - The signing key ID is stored at issuance — key rotation does not invalidate tokens.
 */

import { randomBytes, createHmac, timingSafeEqual } from "crypto";
import { VhyxSealError, ErrorCode } from "../errors/index.js";
import { getActiveKey, listKeys } from "../keys/index.js";
import { createDomainRegistry } from "../registry/domain-registry.js";
import type { DomainRegistry } from "../registry/domain-registry.js";
import { logAudit } from "../audit/index.js";

// ---------------------------------------------------------------------------
// Module-level state
// ---------------------------------------------------------------------------

/** TTL for issued domain verification tokens — 30 days in milliseconds. */
const TTL_MS = 30 * 24 * 60 * 60 * 1000;

/**
 * A domain verification entry in the HMAC-signed token store.
 * The `token` is the raw hex string returned to the caller.
 * The `hmacSignature` is the HMAC-SHA256 digest of "domain:token".
 * The `keyId` is the ID of the signing key used at issuance — stored so that
 * key rotation does not invalidate existing tokens (Session 5-001 Item 1).
 */
interface VerificationEntry {
  readonly token: string;
  readonly hmacSignature: string;
  readonly keyId: string;         // ID of key used at issuance (DECISION-DEFER-2 fix)
  readonly expiresAt: number;     // Unix ms
}

/**
 * Primary store: maps domain → HMAC-signed verification entry.
 * Cleared by clearDomainVerification() for test isolation.
 */
const verificationStore = new Map<string, VerificationEntry>();

/** Tracks domains that have passed HMAC verification at least once. */
const verifiedDomainsSet = new Set<string>();

/**
 * Domain lifecycle manager: tracks domain registration and revocation.
 * Both verificationStore and registry are kept in sync on issue and revoke.
 */
const registry: DomainRegistry = createDomainRegistry();

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Computes an HMAC-SHA256 hex digest over the string "domain:token".
 *
 * The domain prefix ensures tokens cannot be replayed across domains even
 * if two domains happen to have the same raw token bytes (birthday problem
 * mitigation for the HMAC input space).
 *
 * @param domain - The domain to include in the HMAC input.
 * @param token - The raw hex token string.
 * @param secret - The key material as a hex string (from SigningKeyRecord.secret).
 * @returns A 64-character lowercase hex HMAC-SHA256 digest.
 */
function computeTokenHmac(
  domain: string,
  token: string,
  secret: string,
): string {
  return createHmac("sha256", Buffer.from(secret, "hex"))
    .update(`${domain}:${token}`, "utf8")
    .digest("hex");
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Issues a cryptographically signed domain verification token.
 *
 * The token is a 64-character hex string generated by crypto.randomBytes(32).
 * It is HMAC-SHA256 signed and bound to the provided domain. The signing key's
 * ID is stored alongside the HMAC so that key rotation does not invalidate
 * existing tokens — verification always uses the specific key from issuance.
 *
 * @param domain - The domain to issue a token for. Must be a non-empty string
 *   with no whitespace characters.
 * @returns The raw 64-character hex token string to be given to the domain owner
 *   for verification.
 * @throws {VhyxSealError} VHYX_CONTRACT_VALIDATION_FAILED when domain is empty
 *   or contains whitespace.
 * @throws {VhyxSealError} VHYX_MANIFEST_SIGNING_FAILED when no active signing
 *   key is configured in KeyManager.
 * @example
 * import { registerKey } from "@vhyxseal/core";
 * registerKey("a".repeat(64));
 * const token = issueDomainToken("example.com");
 * // token is a 64-character hex string
 */
export function issueDomainToken(domain: string): string {
  // Step 1: validate domain format
  if (domain.trim().length === 0 || /\s/.test(domain)) {
    throw new VhyxSealError({
      code: ErrorCode.VHYX_CONTRACT_VALIDATION_FAILED,
      message: `issueDomainToken: domain must be a non-empty string with no whitespace characters. Received: "${domain}"`,
      context: { domain },
      severity: "error",
      recoverable: true,
      suggestion:
        "Domain must be a non-empty string with no whitespace characters (e.g. \"example.com\").",
    });
  }

  // Step 2: get active signing key from KeyManager
  const keyRecord = getActiveKey();
  if (keyRecord === null) {
    throw new VhyxSealError({
      code: ErrorCode.VHYX_MANIFEST_SIGNING_FAILED,
      message:
        "issueDomainToken: no active signing key configured in KeyManager.",
      context: { domain },
      severity: "error",
      recoverable: true,
      suggestion:
        "Call registerKey(secret) before issueDomainToken(). The secret must be at least 64 hex characters (32 bytes).",
    });
  }

  // Step 3: generate token — crypto.randomBytes only (Constraint 5 / STAGE-4A-CONSTRAINTS)
  const token = randomBytes(32).toString("hex");

  // Step 4: compute HMAC of "domain:token" using the active key secret
  const hmacSignature = computeTokenHmac(domain, token, keyRecord.secret);

  // Step 5: store the HMAC-signed entry with the signing key's ID
  // Storing keyId ensures verifyDomainToken() can find the correct key
  // even after key rotation (Session 5-001 Item 1 — DEFER-2 fix).
  verificationStore.set(domain, {
    token,
    hmacSignature,
    keyId: keyRecord.keyId,
    expiresAt: Date.now() + TTL_MS,
  });

  // Step 6: register domain in DomainRegistry (real consumer call)
  // DomainRegistry issues its own internal token for domain lifecycle tracking.
  // The returned DomainVerificationToken is not used as the primary token in
  // this flow — the HMAC-signed token from step 3 is what callers receive.
  registry.issueToken(domain);

  // Step 7: emit audit event
  logAudit({
    action: "domain_registered",
    domain,
    componentId: null,
    result: "success",
  });

  // Step 8: return the raw hex token to the caller
  return token;
}

/**
 * Verifies a domain verification token against the stored HMAC signature.
 *
 * All six verification steps are performed in order. Returns false on the
 * first failure. Never throws — all internal errors are caught and converted
 * to false returns.
 *
 * The signing key is identified by the keyId stored at issuance — not by the
 * currently active key. This means key rotation does not invalidate tokens
 * that were issued before the rotation.
 *
 * Verification steps:
 *   1. Domain is registered in DomainRegistry.
 *   2. A HMAC-signed entry exists in the verification store.
 *   3. The provided token matches the stored token (tamper check).
 *   4. The token has not expired.
 *   5. The signing key from issuance is retrievable from KeyManager by stored keyId.
 *   6. The recomputed HMAC matches the stored signature (constant-time compare).
 *
 * @param domain - The domain whose token is being verified.
 * @param token - The token string returned by issueDomainToken.
 * @returns true only when all verification checks pass; false otherwise.
 * @example
 * registerKey("a".repeat(64));
 * const token = issueDomainToken("example.com");
 * verifyDomainToken("example.com", token); // true
 * verifyDomainToken("example.com", "wrong"); // false
 */
export function verifyDomainToken(domain: string, token: string): boolean {
  try {
    // Step 1: domain must be registered in DomainRegistry
    if (registry.getToken(domain) === undefined) {
      return false;
    }

    // Step 2: HMAC-signed entry must exist in verificationStore
    const entry = verificationStore.get(domain);
    if (entry === undefined) {
      return false;
    }

    // Step 3: token must match the stored token (mismatch = tampered or wrong token)
    if (entry.token !== token) {
      return false;
    }

    // Step 4: token must not be expired
    if (Date.now() >= entry.expiresAt) {
      return false;
    }

    // Step 5: look up the specific key used at issuance by stored keyId.
    // Using the stored keyId (not getActiveKey()) ensures tokens remain valid
    // after key rotation. If the key was fully removed from KeyManager,
    // return false — the token cannot be verified.
    const allKeys = listKeys();
    const keyRecord = allKeys.find((k) => k.keyId === entry.keyId);
    if (keyRecord === undefined) {
      return false;
    }

    // Step 6: recompute HMAC and compare with stored signature (constant-time)
    const recomputed = computeTokenHmac(domain, token, keyRecord.secret);

    const recomputedBuf = Buffer.from(recomputed, "hex");
    const storedBuf = Buffer.from(entry.hmacSignature, "hex");

    if (recomputedBuf.length !== storedBuf.length) {
      return false;
    }

    const verified = timingSafeEqual(recomputedBuf, storedBuf);
    if (verified) {
      verifiedDomainsSet.add(domain);
      logAudit({
        action: "domain_verified",
        domain,
        componentId: null,
        result: "success",
      });
    }
    return verified;
  } catch {
    return false;
  }
}

/**
 * Revokes a domain verification token, removing it from both the verification
 * store and DomainRegistry.
 *
 * Silent no-op if the domain is not registered — no error is thrown.
 *
 * @param domain - The domain whose token should be revoked.
 * @example
 * revokeDomainToken("example.com");
 * verifyDomainToken("example.com", token); // false after revocation
 */
export function revokeDomainToken(domain: string): void {
  // Remove from DomainRegistry (real consumer call)
  registry.revokeToken(domain);
  // Remove from verificationStore
  verificationStore.delete(domain);
  verifiedDomainsSet.delete(domain);
}

/**
 * Clears all domain verification state from both the verification store and
 * DomainRegistry.
 *
 * For test isolation only. Do not call in production.
 *
 * @internal
 */
export function clearDomainVerification(): void {
  // Revoke all domains from DomainRegistry before clearing the store
  // so both internal data structures are consistent.
  for (const domain of verificationStore.keys()) {
    registry.revokeToken(domain);
  }
  verificationStore.clear();
  verifiedDomainsSet.clear();
}

/**
 * Returns domain verification statistics from the in-memory verification store.
 * Used by the audit dashboard route to surface domain health data.
 *
 * "Verified" means verifyDomainToken() returned true for this domain at least once.
 * "Registered" means issueDomainToken() was called for this domain.
 * tokenExpiry is null when the token has already expired.
 *
 * @returns Statistics object with counts and per-domain details
 */
export function getDomainVerificationStats(): {
  readonly registeredDomains: number;
  readonly verifiedDomains: number;
  readonly domains: ReadonlyArray<{
    readonly domain: string;
    readonly verified: boolean;
    readonly tokenExpiry: string | null;
  }>;
} {
  const domains: Array<{
    readonly domain: string;
    readonly verified: boolean;
    readonly tokenExpiry: string | null;
  }> = [];
  for (const [domain, entry] of verificationStore) {
    const notExpired = Date.now() < entry.expiresAt;
    domains.push({
      domain,
      verified: verifiedDomainsSet.has(domain),
      tokenExpiry: notExpired
        ? new Date(entry.expiresAt).toISOString()
        : null,
    });
  }
  return {
    registeredDomains: verificationStore.size,
    verifiedDomains: verifiedDomainsSet.size,
    domains,
  };
}
